"""enable_chat_translation

Revision ID: 853cc4ff26b5
Revises: 7f726bad5367
Create Date: 2024-02-05 14:54:09.485586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "853cc4ff26b5"
down_revision = "7f726bad5367"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "chat_message", sa.Column("language", sa.Text(), nullable=False)
    )
    op.add_column(
        "chat_message", sa.Column("luganda_message", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_message", "luganda_message")
    op.drop_column("chat_message", "language")
    # ### end Alembic commands ###
